# Texts for the language pages of the public site. Station names stay in English, as on the map.
# Placeholders: {a} {b} {c} {d} station names; {s0}.. fares (silver), {g0} {g2} gold, {r0} {r2} red.
TX = {
"en": dict(
 file="index.html", locale="en_US", dir="ltr",
 title="Interactive Dubai Metro Map: Metro, Tram, Palm Monorail",
 desc="Free, unofficial interactive map of the Dubai Metro, Tram and Palm Monorail. Tap two stations to see the travel time, Nol fare, changes and walking. Also a route planner from the airport, Dubai Mall, Marina, JBR or Atlantis, in 10 languages.",
 ogTitle="Interactive Dubai Metro Map",
 ogDesc="Tap two stations: travel time, Nol fare, changes and walking. Metro, Tram and Palm Monorail. Free, in 10 languages.",
 h1="Interactive Dubai Metro map",
 intro="An unofficial, free interactive map of the Dubai Metro, the Dubai Tram and the Palm Monorail. Tap a station, then another one, and the map shows the trip: travel time, stops, every change, the walking parts and the Nol fare; you can also type a place or a station. It works in English, Hindi, Arabic, Urdu, Russian, German, French, Chinese, Filipino and Bengali, on phones and computers, with nothing to install. After the first visit it also works offline, it can be added to your phone's home screen like an app, and the location button finds the station nearest to you.",
 popular="Popular trips",
 trips=["Dubai Airport (DXB Terminal 3) to Dubai Mall and Burj Khalifa","Dubai Airport (DXB Terminal 1) to Dubai Marina","Dubai Airport to JBR The Walk","Dubai Mall to Atlantis The Palm","Dubai Mall to the Gold Souk","Al Fahidi (Old Dubai) to the Museum of the Future","Dubai Marina to Mall of the Emirates and Ski Dubai","Dubai Mall to Expo City Dubai"],
 lines="Lines and stations",
 red="<b>Red Line:</b> {a} to {b}, with a branch from {c} to {d}.", branch="Branch",
 green="<b>Green Line:</b> {a} to {b}. Changes with the Red Line at Union and BurJuman.",
 tram="<b>Dubai Tram:</b> Al Sufouh to the loop at Dubai Marina and JBR. Walking links to the Metro at Dubai Marina (Sobha Realty) and Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail:</b> {a} to {b}, along the Palm Jumeirah. It is run by a private operator and is not part of the Nol system.",
 susp=" At the time of the last update the operator listed it as temporarily suspended.",
 faq="Questions",
 q=[("What are the Dubai Metro opening hours?","Usually 5:00 to midnight Monday to Thursday and Saturday, 5:00 to 1:00 on Friday night, and 8:00 to midnight on Sunday. The Tram runs about 6:00 to 1:00 (from 9:00 on Sunday). Hours change during Ramadan and on public holidays; check RTA before a late trip."),
    ("How much does the Metro cost?","Fares depend on how many zones you cross. With a Silver Nol card: AED {s0} within one zone, AED {s1} across two zones and AED {s2} for three or more. Gold Class costs AED {g0} to {g2}, a paper Red ticket AED {r0} to {r2}. The planner shows the estimate for each trip."),
    ("Can I get from the airport to the city by Metro?","Yes. Airport Terminal 1 and Terminal 3 are on the Red Line, linked to the terminals. Dubai Mall and Burj Khalifa are about 40 to 45 minutes away with no changes; Dubai Marina takes about an hour, JBR a little longer."),
    ("Is this the official RTA map?","No. This is an independent, non-commercial project and is not affiliated with RTA. Travel times are estimates based on the RTA timetable; always follow signs and announcements at the station.")],
 report="Report a problem or suggest an improvement", close="Close", langName="English"),

"hi": dict(
 file="hi.html", locale="hi_IN", dir="ltr",
 title="इंटरैक्टिव दुबई मेट्रो मैप: मेट्रो, ट्राम, पाम मोनोरेल",
 desc="दुबई मेट्रो, ट्राम और पाम मोनोरेल का मुफ़्त, अनौपचारिक इंटरैक्टिव मैप। दो स्टेशनों पर टैप करें और यात्रा का समय, Nol किराया, बदलाव और पैदल रास्ता देखें। एयरपोर्ट, दुबई मॉल, मरीना, JBR या अटलांटिस के लिए रूट प्लानर भी, 10 भाषाओं में।",
 ogTitle="इंटरैक्टिव दुबई मेट्रो मैप",
 ogDesc="दो स्टेशनों पर टैप करें: यात्रा का समय, Nol किराया, बदलाव और पैदल रास्ता। मेट्रो, ट्राम और पाम मोनोरेल। मुफ़्त, 10 भाषाओं में।",
 h1="इंटरैक्टिव दुबई मेट्रो मैप",
 intro="दुबई मेट्रो, दुबई ट्राम और पाम मोनोरेल का एक अनौपचारिक, मुफ़्त इंटरैक्टिव मैप। एक स्टेशन पर टैप करें, फिर दूसरे पर, और मैप पूरी यात्रा दिखाएगा: यात्रा का समय, स्टॉप, हर बदलाव, पैदल हिस्से और Nol किराया; आप कोई जगह या स्टेशन लिख भी सकते हैं। यह अंग्रेज़ी, हिंदी, अरबी, उर्दू, रूसी, जर्मन, फ़्रेंच, चीनी, फ़िलिपिनो और बांग्ला में, फ़ोन और कंप्यूटर दोनों पर चलता है, कुछ भी इंस्टॉल करने की ज़रूरत नहीं। पहली बार खोलने के बाद यह बिना इंटरनेट के भी चलता है, इसे ऐप की तरह फ़ोन की होम स्क्रीन पर जोड़ा जा सकता है, और लोकेशन बटन आपके सबसे पास का स्टेशन ढूँढ देता है।",
 popular="लोकप्रिय यात्राएँ",
 trips=["दुबई एयरपोर्ट (DXB टर्मिनल 3) से दुबई मॉल और बुर्ज ख़लीफ़ा","दुबई एयरपोर्ट (DXB टर्मिनल 1) से दुबई मरीना","दुबई एयरपोर्ट से JBR The Walk","दुबई मॉल से अटलांटिस द पाम","दुबई मॉल से गोल्ड सूक","अल फ़हीदी (पुराना दुबई) से म्यूज़ियम ऑफ़ द फ़्यूचर","दुबई मरीना से मॉल ऑफ़ द एमिरेट्स और स्की दुबई","दुबई मॉल से एक्सपो सिटी दुबई"],
 lines="लाइनें और स्टेशन",
 red="<b>रेड लाइन:</b> {a} से {b} तक, और {c} से {d} तक एक शाखा।", branch="शाखा",
 green="<b>ग्रीन लाइन:</b> {a} से {b} तक। Union और BurJuman पर रेड लाइन से बदल सकते हैं।",
 tram="<b>दुबई ट्राम:</b> Al Sufouh से Dubai Marina और JBR के लूप तक। Dubai Marina (Sobha Realty) और Jumeirah Lakes Towers (DMCC) पर मेट्रो तक पैदल रास्ता।",
 mono="<b>पाम मोनोरेल:</b> {a} से {b} तक, पाम जुमेराह के साथ-साथ। इसे एक निजी कंपनी चलाती है और यह Nol सिस्टम का हिस्सा नहीं है।",
 susp=" पिछले अपडेट के समय ऑपरेटर के अनुसार सेवा अस्थायी रूप से बंद थी।",
 faq="अक्सर पूछे जाने वाले सवाल",
 q=[("दुबई मेट्रो किस समय चलती है?","आम तौर पर सोमवार से गुरुवार और शनिवार को सुबह 5:00 से आधी रात तक, शुक्रवार को सुबह 5:00 से रात 1:00 तक, और रविवार को सुबह 8:00 से आधी रात तक। ट्राम लगभग सुबह 6:00 से रात 1:00 तक चलती है (रविवार को 9:00 से)। रमज़ान और छुट्टियों में समय बदलता है; देर रात की यात्रा से पहले RTA पर देख लें।"),
    ("मेट्रो का किराया कितना है?","किराया इस पर निर्भर करता है कि आप कितने ज़ोन पार करते हैं। Silver Nol कार्ड से: एक ज़ोन में AED {s0}, दो ज़ोन में AED {s1} और तीन या अधिक ज़ोन में AED {s2}। Gold Class का किराया AED {g0} से {g2} और काग़ज़ के Red टिकट का AED {r0} से {r2} है। प्लानर हर यात्रा का अनुमानित किराया दिखाता है।"),
    ("क्या एयरपोर्ट से शहर मेट्रो से जा सकते हैं?","हाँ। Airport Terminal 1 और Terminal 3 स्टेशन रेड लाइन पर हैं और टर्मिनलों से जुड़े हैं। दुबई मॉल और बुर्ज ख़लीफ़ा बिना बदले लगभग 40 से 45 मिनट में; दुबई मरीना लगभग एक घंटे में, JBR थोड़ा ज़्यादा।"),
    ("क्या यह RTA का आधिकारिक मैप है?","नहीं। यह एक स्वतंत्र, गैर-व्यावसायिक प्रोजेक्ट है और RTA से जुड़ा नहीं है। यात्रा का समय RTA की समय-सारिणी पर आधारित अनुमान है; स्टेशन पर हमेशा संकेतों और घोषणाओं का पालन करें।")],
 report="समस्या बताएँ या सुधार सुझाएँ", close="बंद करें", langName="हिन्दी"),

"ar": dict(
 file="ar.html", locale="ar_AE", dir="rtl",
 title="خريطة مترو دبي التفاعلية: المترو والترام ومونوريل النخلة",
 desc="خريطة تفاعلية مجانية وغير رسمية لمترو دبي والترام ومونوريل النخلة. اضغط على محطتين لترى مدة الرحلة وأجرة نول والتبديلات والمشي. وفيها أيضًا مخطط رحلات من المطار إلى دبي مول ودبي مارينا وJBR وأتلانتس، بعشر لغات.",
 ogTitle="خريطة مترو دبي التفاعلية",
 ogDesc="اضغط على محطتين: مدة الرحلة وأجرة نول والتبديلات والمشي. المترو والترام ومونوريل النخلة. مجانًا وبعشر لغات.",
 h1="خريطة مترو دبي التفاعلية",
 intro="خريطة تفاعلية مجانية وغير رسمية لمترو دبي وترام دبي ومونوريل النخلة. اضغط على محطة ثم على محطة أخرى، فتعرض الخريطة الرحلة: مدتها وعدد المحطات وكل تبديل والأجزاء التي تُقطع سيرًا وأجرة نول، ويمكنك أيضًا كتابة اسم مكان أو محطة. يعمل بالإنجليزية والهندية والعربية والأردية والروسية والألمانية والفرنسية والصينية والفلبينية والبنغالية، على الهاتف والكمبيوتر، دون أي تثبيت. بعد الزيارة الأولى يعمل أيضًا دون اتصال بالإنترنت، ويمكن إضافته إلى الشاشة الرئيسية للهاتف كتطبيق، ويعثر زر الموقع على أقرب محطة إليك.",
 popular="رحلات شائعة",
 trips=["من مطار دبي (DXB المبنى 3) إلى دبي مول وبرج خليفة","من مطار دبي (DXB المبنى 1) إلى دبي مارينا","من مطار دبي إلى JBR The Walk","من دبي مول إلى أتلانتس النخلة","من دبي مول إلى سوق الذهب","من الفهيدي (دبي القديمة) إلى متحف المستقبل","من دبي مارينا إلى مول الإمارات وسكي دبي","من دبي مول إلى إكسبو سيتي دبي"],
 lines="الخطوط والمحطات",
 red="<b>الخط الأحمر:</b> من {a} إلى {b}، مع فرع من {c} إلى {d}.", branch="الفرع",
 green="<b>الخط الأخضر:</b> من {a} إلى {b}. التبديل إلى الخط الأحمر في محطتي Union وBurJuman.",
 tram="<b>ترام دبي:</b> من Al Sufouh إلى الحلقة عند Dubai Marina وJBR. ممرات مشاة إلى المترو عند Dubai Marina (Sobha Realty) وJumeirah Lakes Towers (DMCC).",
 mono="<b>مونوريل النخلة:</b> من {a} إلى {b} على امتداد نخلة جميرا. تديره شركة خاصة وليس جزءًا من نظام نول.",
 susp=" عند آخر تحديث، كان المشغّل يشير إلى توقف الخدمة مؤقتًا.",
 faq="أسئلة شائعة",
 q=[("ما مواعيد تشغيل مترو دبي؟","عادةً من 5:00 صباحًا حتى منتصف الليل من الاثنين إلى الخميس ويوم السبت، ومن 5:00 صباحًا حتى 1:00 بعد منتصف الليل يوم الجمعة، ومن 8:00 صباحًا حتى منتصف الليل يوم الأحد. يعمل الترام تقريبًا من 6:00 صباحًا حتى 1:00 بعد منتصف الليل (من 9:00 يوم الأحد). تتغير المواعيد في رمضان والعطلات الرسمية، لذا تحقّق من هيئة الطرق والمواصلات قبل الرحلات المتأخرة."),
    ("كم تبلغ أجرة المترو؟","تعتمد الأجرة على عدد المناطق التي تعبرها. باستخدام بطاقة نول الفضية: AED {s0} داخل منطقة واحدة، وAED {s1} عبر منطقتين، وAED {s2} لثلاث مناطق أو أكثر. تكلفة الدرجة الذهبية من AED {g0} إلى {g2}، والتذكرة الحمراء الورقية من AED {r0} إلى {r2}. يعرض المخطط الأجرة التقديرية لكل رحلة."),
    ("هل يمكن الوصول من المطار إلى المدينة بالمترو؟","نعم. محطتا Airport Terminal 1 وTerminal 3 على الخط الأحمر ومتصلتان بمباني المطار. يستغرق الوصول إلى دبي مول وبرج خليفة نحو 40 إلى 45 دقيقة دون تبديل، وإلى دبي مارينا نحو ساعة، وإلى JBR أكثر قليلًا."),
    ("هل هذه الخريطة الرسمية لهيئة الطرق والمواصلات؟","لا. هذا مشروع مستقل وغير تجاري ولا يرتبط بهيئة الطرق والمواصلات. مدة الرحلات تقديرية بناءً على جداول الهيئة، لذا اتّبع دائمًا اللافتات والإعلانات في المحطة.")],
 report="الإبلاغ عن مشكلة أو اقتراح تحسين", close="إغلاق", langName="العربية"),

"ur": dict(
 file="ur.html", locale="ur_PK", dir="rtl",
 title="دبئی میٹرو کا انٹرایکٹو نقشہ: میٹرو، ٹرام، پام مونو ریل",
 desc="دبئی میٹرو، ٹرام اور پام مونو ریل کا مفت، غیر سرکاری انٹرایکٹو نقشہ۔ دو اسٹیشنوں پر ٹیپ کریں اور سفر کا وقت، Nol کرایہ، تبدیلیاں اور پیدل راستہ دیکھیں۔ ایئرپورٹ، دبئی مال، مرینا، JBR یا اٹلانٹس کے لیے روٹ پلانر بھی، 10 زبانوں میں۔",
 ogTitle="دبئی میٹرو کا انٹرایکٹو نقشہ",
 ogDesc="دو اسٹیشنوں پر ٹیپ کریں: سفر کا وقت، Nol کرایہ، تبدیلیاں اور پیدل راستہ۔ میٹرو، ٹرام اور پام مونو ریل۔ مفت، 10 زبانوں میں۔",
 h1="دبئی میٹرو کا انٹرایکٹو نقشہ",
 intro="دبئی میٹرو، دبئی ٹرام اور پام مونو ریل کا ایک غیر سرکاری، مفت انٹرایکٹو نقشہ۔ ایک اسٹیشن پر ٹیپ کریں، پھر دوسرے پر، اور نقشہ پورا سفر دکھائے گا: سفر کا وقت، اسٹاپ، ہر تبدیلی، پیدل حصے اور Nol کرایہ؛ آپ کوئی جگہ یا اسٹیشن لکھ بھی سکتے ہیں۔ یہ انگریزی، ہندی، عربی، اردو، روسی، جرمن، فرانسیسی، چینی، فلپائنی اور بنگالی میں، فون اور کمپیوٹر دونوں پر چلتا ہے، کچھ انسٹال کرنے کی ضرورت نہیں۔ پہلی بار کھولنے کے بعد یہ انٹرنیٹ کے بغیر بھی چلتا ہے، اسے ایپ کی طرح فون کی ہوم اسکرین پر لگایا جا سکتا ہے، اور لوکیشن بٹن آپ کے قریب ترین اسٹیشن کو ڈھونڈ لیتا ہے۔",
 popular="مقبول سفر",
 trips=["دبئی ایئرپورٹ (DXB ٹرمینل 3) سے دبئی مال اور برج خلیفہ","دبئی ایئرپورٹ (DXB ٹرمینل 1) سے دبئی مرینا","دبئی ایئرپورٹ سے JBR The Walk","دبئی مال سے اٹلانٹس دی پام","دبئی مال سے گولڈ سوق","الفہیدی (پرانا دبئی) سے میوزیم آف دی فیوچر","دبئی مرینا سے مال آف دی ایمریٹس اور اسکی دبئی","دبئی مال سے ایکسپو سٹی دبئی"],
 lines="لائنیں اور اسٹیشن",
 red="<b>ریڈ لائن:</b> {a} سے {b} تک، اور {c} سے {d} تک ایک شاخ۔", branch="شاخ",
 green="<b>گرین لائن:</b> {a} سے {b} تک۔ Union اور BurJuman پر ریڈ لائن میں تبدیلی ہوتی ہے۔",
 tram="<b>دبئی ٹرام:</b> Al Sufouh سے Dubai Marina اور JBR کے لوپ تک۔ Dubai Marina (Sobha Realty) اور Jumeirah Lakes Towers (DMCC) پر میٹرو تک پیدل راستہ۔",
 mono="<b>پام مونو ریل:</b> {a} سے {b} تک، پام جمیرا کے ساتھ ساتھ۔ اسے ایک نجی کمپنی چلاتی ہے اور یہ Nol نظام کا حصہ نہیں۔",
 susp=" آخری اپڈیٹ کے وقت آپریٹر کے مطابق سروس عارضی طور پر معطل تھی۔",
 faq="اکثر پوچھے جانے والے سوالات",
 q=[("دبئی میٹرو کس وقت چلتی ہے؟","عام طور پر پیر سے جمعرات اور ہفتے کو صبح 5:00 سے آدھی رات تک، جمعے کو صبح 5:00 سے رات 1:00 بجے تک، اور اتوار کو صبح 8:00 سے آدھی رات تک۔ ٹرام تقریباً صبح 6:00 سے رات 1:00 بجے تک چلتی ہے (اتوار کو 9:00 سے)۔ رمضان اور تعطیلات میں اوقات بدل جاتے ہیں؛ رات دیر کے سفر سے پہلے RTA پر دیکھ لیں۔"),
    ("میٹرو کا کرایہ کتنا ہے؟","کرایہ اس پر منحصر ہے کہ آپ کتنے زون عبور کرتے ہیں۔ Silver Nol کارڈ سے: ایک زون میں AED {s0}، دو زون میں AED {s1} اور تین یا زیادہ زون میں AED {s2}۔ Gold Class کا کرایہ AED {g0} سے {g2} اور کاغذی Red ٹکٹ کا AED {r0} سے {r2} ہے۔ پلانر ہر سفر کا اندازاً کرایہ دکھاتا ہے۔"),
    ("کیا ایئرپورٹ سے شہر میٹرو سے جا سکتے ہیں؟","جی ہاں۔ Airport Terminal 1 اور Terminal 3 اسٹیشن ریڈ لائن پر ہیں اور ٹرمینلز سے جڑے ہیں۔ دبئی مال اور برج خلیفہ بغیر تبدیلی کے تقریباً 40 سے 45 منٹ میں؛ دبئی مرینا تقریباً ایک گھنٹے میں، JBR کچھ زیادہ۔"),
    ("کیا یہ RTA کا سرکاری نقشہ ہے؟","نہیں۔ یہ ایک آزاد، غیر تجارتی منصوبہ ہے اور RTA سے وابستہ نہیں۔ سفر کے اوقات RTA کے ٹائم ٹیبل پر مبنی اندازے ہیں؛ اسٹیشن پر ہمیشہ نشانات اور اعلانات پر عمل کریں۔")],
 report="مسئلہ رپورٹ کریں یا بہتری تجویز کریں", close="بند کریں", langName="اردو"),

"ru": dict(
 file="ru.html", locale="ru_RU", dir="ltr",
 title="Интерактивная карта метро Дубая: метро, трамвай, монорельс",
 desc="Бесплатная неофициальная интерактивная карта метро, трамвая и монорельса Palm в Дубае. Нажмите на две станции и увидите время в пути, цену Nol, пересадки и пешие участки. Есть и построение маршрута из аэропорта до Dubai Mall, Марины, JBR и Atlantis, на 10 языках.",
 ogTitle="Интерактивная карта метро Дубая",
 ogDesc="Нажмите на две станции: время в пути, цена Nol, пересадки и пешие участки. Метро, трамвай и монорельс Palm. Бесплатно, на 10 языках.",
 h1="Интерактивная карта метро Дубая",
 intro="Неофициальная бесплатная интерактивная карта метро Дубая, трамвая и монорельса Palm. Нажмите на одну станцию, потом на другую, и карта покажет поездку: время в пути, остановки, все пересадки, пешие участки и цену по карте Nol; можно и ввести место или станцию. Сайт работает на английском, хинди, арабском, урду, русском, немецком, французском, китайском, филиппинском и бенгальском, на телефоне и компьютере, ничего устанавливать не нужно. После первого открытия сайт работает и без интернета, его можно добавить на главный экран телефона как приложение, а кнопка геолокации найдёт ближайшую к вам станцию.",
 popular="Популярные маршруты",
 trips=["Из аэропорта Дубая (DXB, терминал 3) до Dubai Mall и Бурдж-Халифы","Из аэропорта Дубая (DXB, терминал 1) до Dubai Marina","Из аэропорта Дубая до JBR The Walk","От Dubai Mall до Atlantis The Palm","От Dubai Mall до Золотого рынка","От Аль-Фахиди (старый Дубай) до Музея будущего","От Dubai Marina до Mall of the Emirates и Ski Dubai","От Dubai Mall до Expo City Dubai"],
 lines="Линии и станции",
 red="<b>Красная линия:</b> от {a} до {b}, с ответвлением от {c} до {d}.", branch="Ответвление",
 green="<b>Зелёная линия:</b> от {a} до {b}. Пересадка на Красную линию на станциях Union и BurJuman.",
 tram="<b>Трамвай Дубая:</b> от Al Sufouh до кольца у Dubai Marina и JBR. Пешие переходы к метро у станций Dubai Marina (Sobha Realty) и Jumeirah Lakes Towers (DMCC).",
 mono="<b>Монорельс Palm:</b> от {a} до {b}, вдоль острова Пальма Джумейра. Им управляет частный оператор, карта Nol на нём не действует.",
 susp=" На момент последнего обновления оператор сообщал, что движение временно приостановлено.",
 faq="Частые вопросы",
 q=[("Во сколько работает метро Дубая?","Обычно с 5:00 до полуночи с понедельника по четверг и в субботу, с 5:00 до 1:00 ночи в пятницу и с 8:00 до полуночи в воскресенье. Трамвай ходит примерно с 6:00 до 1:00 (в воскресенье с 9:00). В Рамадан и праздники часы меняются; перед поздней поездкой проверьте на сайте RTA."),
    ("Сколько стоит проезд в метро?","Цена зависит от того, сколько зон вы пересекаете. По серебряной карте Nol: AED {s0} в пределах одной зоны, AED {s1} через две зоны и AED {s2} за три и больше. Gold Class стоит от AED {g0} до {g2}, бумажный Red ticket от AED {r0} до {r2}. Планировщик показывает примерную цену для каждой поездки."),
    ("Можно ли доехать из аэропорта в город на метро?","Да. Станции Airport Terminal 1 и Terminal 3 находятся на Красной линии и соединены с терминалами. До Dubai Mall и Бурдж-Халифы около 40–45 минут без пересадок, до Dubai Marina около часа, до JBR немного дольше."),
    ("Это официальная карта RTA?","Нет. Это независимый некоммерческий проект, не связанный с RTA. Время в пути рассчитано по расписанию RTA и является оценкой; на станции всегда ориентируйтесь на указатели и объявления.")],
 report="Сообщить об ошибке или предложить улучшение", close="Закрыть", langName="Русский"),

"de": dict(
 file="de.html", locale="de_DE", dir="ltr",
 title="Interaktive Dubai Metro Karte: Metro, Tram, Palm Monorail",
 desc="Kostenlose, inoffizielle interaktive Karte der Dubai Metro, Tram und Palm Monorail. Tippen Sie auf zwei Stationen und sehen Sie Fahrzeit, Nol-Preis, Umstiege und Fußwege. Dazu ein Routenplaner vom Flughafen zur Dubai Mall, Marina, JBR oder zum Atlantis, in 10 Sprachen.",
 ogTitle="Interaktive Dubai Metro Karte",
 ogDesc="Zwei Stationen antippen: Fahrzeit, Nol-Preis, Umstiege und Fußwege. Metro, Tram und Palm Monorail. Kostenlos, in 10 Sprachen.",
 h1="Interaktive Dubai Metro Karte",
 intro="Eine inoffizielle, kostenlose interaktive Karte der Dubai Metro, der Dubai Tram und der Palm Monorail. Tippen Sie auf eine Station und dann auf eine zweite: Die Karte zeigt die Fahrt mit Fahrzeit, Haltestellen, allen Umstiegen, den Fußwegen und dem Nol-Preis; Sie können auch einen Ort oder eine Station eingeben. Sie funktioniert auf Englisch, Hindi, Arabisch, Urdu, Russisch, Deutsch, Französisch, Chinesisch, Filipino und Bengalisch, auf Handy und Computer, ohne Installation. Nach dem ersten Besuch funktioniert er auch offline, lässt sich wie eine App auf den Startbildschirm legen, und die Standorttaste findet die nächste Station.",
 popular="Beliebte Strecken",
 trips=["Flughafen Dubai (DXB Terminal 3) zur Dubai Mall und zum Burj Khalifa","Flughafen Dubai (DXB Terminal 1) zur Dubai Marina","Flughafen Dubai nach JBR The Walk","Dubai Mall zum Atlantis The Palm","Dubai Mall zum Gold Souk","Al Fahidi (Altstadt) zum Museum of the Future","Dubai Marina zur Mall of the Emirates und zu Ski Dubai","Dubai Mall zur Expo City Dubai"],
 lines="Linien und Stationen",
 red="<b>Rote Linie:</b> {a} bis {b}, mit einem Abzweig von {c} nach {d}.", branch="Abzweig",
 green="<b>Grüne Linie:</b> {a} bis {b}. Umstieg zur Roten Linie in Union und BurJuman.",
 tram="<b>Dubai Tram:</b> Al Sufouh bis zur Schleife an Dubai Marina und JBR. Fußwege zur Metro an Dubai Marina (Sobha Realty) und Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail:</b> {a} bis {b}, entlang der Palm Jumeirah. Sie wird von einem privaten Betreiber betrieben und gehört nicht zum Nol-System.",
 susp=" Zum Zeitpunkt der letzten Aktualisierung meldete der Betreiber, dass der Betrieb vorübergehend eingestellt ist.",
 faq="Häufige Fragen",
 q=[("Wann fährt die Dubai Metro?","In der Regel Montag bis Donnerstag und Samstag von 5:00 bis Mitternacht, freitags von 5:00 bis 1:00 Uhr nachts und sonntags von 8:00 bis Mitternacht. Die Tram fährt etwa von 6:00 bis 1:00 Uhr (sonntags ab 9:00). Im Ramadan und an Feiertagen gelten andere Zeiten; prüfen Sie vor einer späten Fahrt die Angaben der RTA."),
    ("Was kostet die Metro?","Der Preis hängt davon ab, wie viele Zonen Sie durchfahren. Mit der Silver-Nol-Karte: AED {s0} innerhalb einer Zone, AED {s1} über zwei Zonen und AED {s2} ab drei Zonen. Gold Class kostet AED {g0} bis {g2}, ein Red Ticket aus Papier AED {r0} bis {r2}. Der Planer zeigt für jede Fahrt den geschätzten Preis."),
    ("Kommt man mit der Metro vom Flughafen in die Stadt?","Ja. Airport Terminal 1 und Terminal 3 liegen an der Roten Linie und sind mit den Terminals verbunden. Bis zur Dubai Mall und zum Burj Khalifa sind es etwa 40 bis 45 Minuten ohne Umstieg, bis zur Dubai Marina etwa eine Stunde, bis JBR etwas länger."),
    ("Ist das die offizielle Karte der RTA?","Nein. Dies ist ein unabhängiges, nicht kommerzielles Projekt ohne Verbindung zur RTA. Die Fahrzeiten sind Schätzungen auf Grundlage des RTA-Fahrplans; achten Sie an der Station immer auf Schilder und Durchsagen.")],
 report="Fehler melden oder Verbesserung vorschlagen", close="Schließen", langName="Deutsch"),

"zh": dict(
 file="zh.html", locale="zh_CN", dir="ltr",
 title="迪拜地铁互动线路图：地铁、有轨电车、棕榈岛单轨",
 desc="免费的非官方迪拜地铁、有轨电车和棕榈岛单轨互动线路图。点击两个车站，即可查看行程时间、Nol 票价、换乘和步行路段。也可从机场规划前往迪拜购物中心、迪拜码头、JBR 或亚特兰蒂斯的路线，支持 10 种语言。",
 ogTitle="迪拜地铁互动线路图",
 ogDesc="点击两个车站：行程时间、Nol 票价、换乘和步行。地铁、有轨电车和棕榈岛单轨。免费，支持 10 种语言。",
 h1="迪拜地铁互动线路图",
 intro="这是一份免费的非官方迪拜地铁、迪拜有轨电车和棕榈岛单轨互动线路图。点击一个车站，再点击另一个车站，地图就会显示整段行程：行程时间、站数、每次换乘、步行路段和 Nol 票价；也可以输入地点或车站。支持英语、印地语、阿拉伯语、乌尔都语、俄语、德语、法语、中文、菲律宾语和孟加拉语，手机和电脑均可使用，无需安装。首次打开后即可离线使用，还可以像应用一样添加到手机主屏幕，定位按钮会帮您找到最近的车站。",
 popular="热门路线",
 trips=["迪拜机场（DXB 3 号航站楼）到迪拜购物中心和哈利法塔","迪拜机场（DXB 1 号航站楼）到迪拜码头","迪拜机场到 JBR The Walk","迪拜购物中心到亚特兰蒂斯酒店","迪拜购物中心到黄金市场","Al Fahidi 历史街区（老城）到未来博物馆","迪拜码头到阿联酋购物中心和迪拜滑雪场","迪拜购物中心到迪拜世博城"],
 lines="线路与车站",
 red="<b>红线：</b>{a} 至 {b}，另有一条支线从 {c} 至 {d}。", branch="支线",
 green="<b>绿线：</b>{a} 至 {b}。可在 Union 和 BurJuman 站换乘红线。",
 tram="<b>迪拜有轨电车：</b>从 Al Sufouh 至 Dubai Marina 和 JBR 的环线。在 Dubai Marina（Sobha Realty）和 Jumeirah Lakes Towers（DMCC）可步行换乘地铁。",
 mono="<b>棕榈岛单轨：</b>{a} 至 {b}，沿朱美拉棕榈岛运行。由私营公司运营，不属于 Nol 系统。",
 susp="截至最近一次更新，运营方显示该线路暂停运营。",
 faq="常见问题",
 q=[("迪拜地铁的运营时间是几点？","通常周一至周四及周六为 5:00 至午夜，周五为 5:00 至次日 1:00，周日为 8:00 至午夜。有轨电车约 6:00 至次日 1:00 运营（周日 9:00 起）。斋月和节假日时间会调整，深夜出行前请查看 RTA 信息。"),
    ("乘坐地铁要多少钱？","票价取决于跨越的区数。使用 Silver Nol 卡：同一区内 AED {s0}，跨两个区 AED {s1}，三个区及以上 AED {s2}。Gold Class 为 AED {g0} 至 {g2}，纸质 Red 票为 AED {r0} 至 {r2}。规划工具会为每次行程显示估算票价。"),
    ("可以从机场乘地铁进城吗？","可以。Airport Terminal 1 和 Terminal 3 站位于红线上，与航站楼相连。到迪拜购物中心和哈利法塔约 40 至 45 分钟，无需换乘；到迪拜码头约一小时，到 JBR 稍长一些。"),
    ("这是 RTA 的官方地图吗？","不是。这是一个独立的非商业项目，与 RTA 无关。行程时间根据 RTA 时刻表估算，请始终以车站的指示牌和广播为准。")],
 report="报告问题或提出改进建议", close="关闭", langName="中文"),

"fr": dict(
 file="fr.html", locale="fr_FR", dir="ltr",
 title="Plan interactif du métro de Dubaï : métro, tram, monorail",
 desc="Plan interactif gratuit et non officiel du métro, du tramway et du Palm Monorail de Dubaï. Touchez deux stations pour voir le temps de trajet, le tarif Nol, les correspondances et la marche. Calcul d'itinéraire depuis l'aéroport, Dubai Mall, la Marina, JBR ou l'Atlantis, en 10 langues.",
 ogTitle="Plan interactif du métro de Dubaï",
 ogDesc="Touchez deux stations : temps de trajet, tarif Nol, correspondances et marche. Métro, tramway et Palm Monorail. Gratuit, en 10 langues.",
 h1="Plan interactif du métro de Dubaï",
 intro="Un plan interactif gratuit et non officiel du métro de Dubaï, du tramway et du Palm Monorail. Touchez une station, puis une autre : le plan affiche le trajet avec le temps de parcours, les arrêts, chaque correspondance, les trajets à pied et le tarif Nol ; vous pouvez aussi saisir un lieu ou une station. Il fonctionne en anglais, hindi, arabe, ourdou, russe, allemand, français, chinois, filipino et bengali, sur téléphone et ordinateur, sans rien installer. Après la première visite, il fonctionne aussi hors connexion, peut être ajouté à l’écran d’accueil du téléphone comme une application, et le bouton de localisation trouve la station la plus proche.",
 popular="Trajets populaires",
 trips=["Aéroport de Dubaï (DXB, terminal 3) vers Dubai Mall et Burj Khalifa","Aéroport de Dubaï (DXB, terminal 1) vers Dubai Marina","Aéroport de Dubaï vers JBR The Walk","Dubai Mall vers Atlantis The Palm","Dubai Mall vers le souk de l'or","Al Fahidi (vieux Dubaï) vers le Musée du Futur","Dubai Marina vers Mall of the Emirates et Ski Dubai","Dubai Mall vers Expo City Dubai"],
 lines="Lignes et stations",
 red="<b>Ligne rouge :</b> de {a} à {b}, avec un embranchement de {c} à {d}.", branch="Embranchement",
 green="<b>Ligne verte :</b> de {a} à {b}. Correspondance avec la ligne rouge à Union et BurJuman.",
 tram="<b>Tramway de Dubaï :</b> d'Al Sufouh jusqu'à la boucle de Dubai Marina et JBR. Liaisons à pied avec le métro à Dubai Marina (Sobha Realty) et Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail :</b> de {a} à {b}, le long de Palm Jumeirah. Il est exploité par un opérateur privé et ne fait pas partie du système Nol.",
 susp=" Lors de la dernière mise à jour, l'opérateur indiquait que le service était temporairement suspendu.",
 faq="Questions fréquentes",
 q=[("Quels sont les horaires du métro de Dubaï ?","En général de 5 h à minuit du lundi au jeudi et le samedi, de 5 h à 1 h dans la nuit du vendredi, et de 8 h à minuit le dimanche. Le tramway circule environ de 6 h à 1 h (à partir de 9 h le dimanche). Les horaires changent pendant le ramadan et les jours fériés ; vérifiez auprès de la RTA avant un trajet tardif."),
    ("Combien coûte le métro ?","Le prix dépend du nombre de zones traversées. Avec une carte Nol Silver : AED {s0} dans une zone, AED {s1} sur deux zones et AED {s2} pour trois zones ou plus. La Gold Class coûte de AED {g0} à {g2}, le ticket papier Red de AED {r0} à {r2}. L'outil indique une estimation pour chaque trajet."),
    ("Peut-on aller de l'aéroport au centre en métro ?","Oui. Les stations Airport Terminal 1 et Terminal 3 sont sur la ligne rouge et reliées aux terminaux. Dubai Mall et Burj Khalifa sont à environ 40 à 45 minutes sans correspondance ; Dubai Marina à environ une heure, JBR un peu plus."),
    ("Est-ce le plan officiel de la RTA ?","Non. C'est un projet indépendant et non commercial, sans lien avec la RTA. Les temps de trajet sont des estimations basées sur les horaires de la RTA ; suivez toujours la signalétique et les annonces en station.")],
 report="Signaler un problème ou proposer une amélioration", close="Fermer", langName="Français"),

"tl": dict(
 file="tl.html", locale="fil_PH", dir="ltr",
 title="Interactive na Mapa ng Dubai Metro: Metro, Tram, Palm Monorail",
 desc="Libre at hindi opisyal na interactive na mapa ng Dubai Metro, Tram at Palm Monorail. Pindutin ang dalawang istasyon para makita ang oras ng biyahe, pamasahe sa Nol, mga lipat at lakad. May route planner din mula sa airport papunta sa Dubai Mall, Marina, JBR o Atlantis, sa 10 wika.",
 ogTitle="Interactive na Mapa ng Dubai Metro",
 ogDesc="Pindutin ang dalawang istasyon: oras ng biyahe, pamasahe sa Nol, mga lipat at lakad. Metro, Tram at Palm Monorail. Libre, sa 10 wika.",
 h1="Interactive na mapa ng Dubai Metro",
 intro="Libre at hindi opisyal na interactive na mapa ng Dubai Metro, Dubai Tram at Palm Monorail. Pindutin ang isang istasyon, pagkatapos ang isa pa, at ipapakita ng mapa ang biyahe: oras, mga hintuan, bawat lipat, ang mga bahaging lalakarin at pamasahe sa Nol; puwede ka ring mag-type ng lugar o istasyon. Gumagana ito sa English, Hindi, Arabic, Urdu, Russian, German, French, Chinese, Filipino at Bengali, sa phone at computer, nang walang ini-install. Pagkatapos ng unang bisita, gumagana rin ito offline, puwede itong idagdag sa home screen ng phone na parang app, at hinahanap ng location button ang pinakamalapit na istasyon.",
 popular="Mga sikat na biyahe",
 trips=["Dubai Airport (DXB Terminal 3) papuntang Dubai Mall at Burj Khalifa","Dubai Airport (DXB Terminal 1) papuntang Dubai Marina","Dubai Airport papuntang JBR The Walk","Dubai Mall papuntang Atlantis The Palm","Dubai Mall papuntang Gold Souk","Al Fahidi (Lumang Dubai) papuntang Museum of the Future","Dubai Marina papuntang Mall of the Emirates at Ski Dubai","Dubai Mall papuntang Expo City Dubai"],
 lines="Mga linya at istasyon",
 red="<b>Red Line:</b> {a} hanggang {b}, may sangay mula {c} hanggang {d}.", branch="Sangay",
 green="<b>Green Line:</b> {a} hanggang {b}. Puwedeng lumipat sa Red Line sa Union at BurJuman.",
 tram="<b>Dubai Tram:</b> mula Al Sufouh hanggang sa ikot sa Dubai Marina at JBR. May lakaran papunta sa Metro sa Dubai Marina (Sobha Realty) at Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail:</b> {a} hanggang {b}, sa kahabaan ng Palm Jumeirah. Pribadong kompanya ang nagpapatakbo nito at hindi ito bahagi ng Nol system.",
 susp=" Noong huling update, nakalista ito ng operator bilang pansamantalang sarado.",
 faq="Mga tanong",
 q=[("Anong oras bukas ang Dubai Metro?","Karaniwan 5:00 hanggang hatinggabi tuwing Lunes hanggang Huwebes at Sabado, 5:00 hanggang 1:00 ng madaling-araw tuwing Biyernes, at 8:00 hanggang hatinggabi tuwing Linggo. Ang Tram ay mga 6:00 hanggang 1:00 (mula 9:00 tuwing Linggo). Nagbabago ang oras tuwing Ramadan at holiday; tingnan ang RTA bago bumiyahe nang gabi na."),
    ("Magkano ang pamasahe sa Metro?","Nakadepende ang pamasahe sa dami ng zone na dadaanan mo. Sa Silver Nol card: AED {s0} sa loob ng isang zone, AED {s1} sa dalawang zone at AED {s2} sa tatlo o higit pa. Ang Gold Class ay AED {g0} hanggang {g2}, ang papel na Red ticket ay AED {r0} hanggang {r2}. Ipinapakita ng planner ang tantiyang pamasahe sa bawat biyahe."),
    ("Puwede bang mag-Metro mula airport papuntang siyudad?","Oo. Nasa Red Line ang Airport Terminal 1 at Terminal 3 at konektado sa mga terminal. Mga 40 hanggang 45 minuto papuntang Dubai Mall at Burj Khalifa nang walang lipat; mga isang oras papuntang Dubai Marina, medyo mas matagal papuntang JBR."),
    ("Ito ba ang opisyal na mapa ng RTA?","Hindi. Isa itong independiyente at hindi pangkomersyong proyekto, walang kaugnayan sa RTA. Tantiya ang oras ng biyahe batay sa timetable ng RTA; laging sundin ang karatula at anunsyo sa istasyon.")],
 report="Mag-ulat ng problema o magmungkahi", close="Isara", langName="Filipino"),

"bn": dict(
 file="bn.html", locale="bn_BD", dir="ltr",
 title="দুবাই মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র: মেট্রো, ট্রাম, পাম মনোরেল",
 desc="দুবাই মেট্রো, ট্রাম ও পাম মনোরেলের বিনামূল্যের, অনানুষ্ঠানিক ইন্টারঅ্যাক্টিভ মানচিত্র। দুটি স্টেশনে চাপুন, দেখুন যাত্রার সময়, Nol ভাড়া, বদল ও হাঁটার পথ। বিমানবন্দর থেকে Dubai Mall, মারিনা, JBR বা আটলান্টিস যাওয়ার রুট প্ল্যানারও আছে, ১০টি ভাষায়।",
 ogTitle="দুবাই মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র",
 ogDesc="দুটি স্টেশনে চাপুন: যাত্রার সময়, Nol ভাড়া, বদল ও হাঁটা। মেট্রো, ট্রাম ও পাম মনোরেল। বিনামূল্যে, ১০টি ভাষায়।",
 h1="দুবাই মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র",
 intro="দুবাই মেট্রো, দুবাই ট্রাম ও পাম মনোরেলের বিনামূল্যের, অনানুষ্ঠানিক ইন্টারঅ্যাক্টিভ মানচিত্র। একটি স্টেশনে চাপুন, তারপর আরেকটিতে, মানচিত্র পুরো যাত্রা দেখাবে: যাত্রার সময়, স্টপ, প্রতিটি বদল, হাঁটার অংশ ও Nol ভাড়া; চাইলে কোনো জায়গা বা স্টেশনের নামও লিখতে পারেন। ইংরেজি, হিন্দি, আরবি, উর্দু, রুশ, জার্মান, ফরাসি, চীনা, ফিলিপিনো ও বাংলায় ফোন ও কম্পিউটারে কিছু ইনস্টল না করেই চলে। প্রথমবার খোলার পর ইন্টারনেট ছাড়াও চলে, অ্যাপের মতো ফোনের হোম স্ক্রিনে যোগ করা যায়, আর লোকেশন বোতাম আপনার সবচেয়ে কাছের স্টেশন খুঁজে দেয়।",
 popular="জনপ্রিয় যাত্রা",
 trips=["দুবাই বিমানবন্দর (DXB টার্মিনাল ৩) থেকে Dubai Mall ও বুর্জ খলিফা","দুবাই বিমানবন্দর (DXB টার্মিনাল ১) থেকে দুবাই মারিনা","দুবাই বিমানবন্দর থেকে JBR The Walk","Dubai Mall থেকে Atlantis The Palm","Dubai Mall থেকে গোল্ড সুক","আল ফাহিদি (পুরোনো দুবাই) থেকে Museum of the Future","দুবাই মারিনা থেকে Mall of the Emirates ও Ski Dubai","Dubai Mall থেকে Expo City Dubai"],
 lines="লাইন ও স্টেশন",
 red="<b>রেড লাইন:</b> {a} থেকে {b}, আর {c} থেকে {d} পর্যন্ত একটি শাখা।", branch="শাখা",
 green="<b>গ্রিন লাইন:</b> {a} থেকে {b}। Union ও BurJuman-এ রেড লাইনে বদলানো যায়।",
 tram="<b>দুবাই ট্রাম:</b> Al Sufouh থেকে Dubai Marina ও JBR-এর চক্কর পর্যন্ত। Dubai Marina (Sobha Realty) ও Jumeirah Lakes Towers (DMCC)-এ হেঁটে মেট্রোতে যাওয়া যায়।",
 mono="<b>পাম মনোরেল:</b> {a} থেকে {b}, পাম জুমেইরাহ বরাবর। এটি একটি বেসরকারি কোম্পানি চালায়, Nol ব্যবস্থার অংশ নয়।",
 susp=" শেষ আপডেটের সময় অপারেটর এটিকে সাময়িকভাবে বন্ধ দেখিয়েছিল।",
 faq="প্রশ্ন",
 q=[("দুবাই মেট্রো কখন চলে?","সাধারণত সোমবার থেকে বৃহস্পতিবার ও শনিবার ভোর ৫টা থেকে মধ্যরাত, শুক্রবার ভোর ৫টা থেকে রাত ১টা, আর রবিবার সকাল ৮টা থেকে মধ্যরাত। ট্রাম চলে মোটামুটি সকাল ৬টা থেকে রাত ১টা (রবিবার সকাল ৯টা থেকে)। রমজান ও সরকারি ছুটিতে সময় বদলায়; রাতে দেরিতে যাওয়ার আগে RTA-তে দেখে নিন।"),
    ("মেট্রোর ভাড়া কত?","ভাড়া নির্ভর করে কয়টি জোন পার হচ্ছেন তার ওপর। Silver Nol কার্ডে: এক জোনের মধ্যে AED {s0}, দুই জোনে AED {s1}, তিন বা তার বেশি জোনে AED {s2}। Gold Class-এর ভাড়া AED {g0} থেকে {g2}, কাগজের Red টিকিট AED {r0} থেকে {r2}। প্ল্যানার প্রতিটি যাত্রার আনুমানিক ভাড়া দেখায়।"),
    ("বিমানবন্দর থেকে কি মেট্রোতে শহরে যাওয়া যায়?","হ্যাঁ। Airport Terminal 1 ও Terminal 3 স্টেশন রেড লাইনে, টার্মিনালের সঙ্গে যুক্ত। Dubai Mall ও বুর্জ খলিফা বদল ছাড়াই প্রায় ৪০ থেকে ৪৫ মিনিট; দুবাই মারিনা প্রায় এক ঘণ্টা, JBR আরেকটু বেশি।"),
    ("এটা কি RTA-র সরকারি মানচিত্র?","না। এটি একটি স্বাধীন, অবাণিজ্যিক প্রকল্প, RTA-র সঙ্গে যুক্ত নয়। যাত্রার সময় RTA-র সময়সূচির ভিত্তিতে আনুমানিক; স্টেশনে সবসময় চিহ্ন ও ঘোষণা মেনে চলুন।")],
 report="সমস্যা জানান বা উন্নতির পরামর্শ দিন", close="বন্ধ করুন", langName="বাংলা"),
}
ORDER=["en","hi","ar","ur","ru","de","zh","fr","tl","bn"]
