# Texts for the language pages of the public site. Station names stay in English, as on the map.
# Placeholders: {a} {b} {c} {d} station names; {s0}.. fares (silver), {g0} {g2} gold, {r0} {r2} red.
TX = {
"en": dict(
 file="index.html", locale="en_US", dir="ltr",
 title="Dubai Metro Map &amp; Route Planner: Metro, Tram, Palm Monorail",
 desc="Free, unofficial Dubai Metro map and journey planner. Get from the airport, Dubai Mall, Marina, JBR or Atlantis by Metro, Tram and Palm Monorail with step-by-step directions, travel times, Nol fares and opening hours, in 8 languages.",
 ogTitle="Dubai Metro Map &amp; Route Planner",
 ogDesc="Metro, Tram and Palm Monorail: directions, travel times, Nol fares and opening hours. Free, in 8 languages.",
 h1="Dubai Metro map and route planner",
 intro="An unofficial, free map of the Dubai Metro, the Dubai Tram and the Palm Monorail. Type a place or a station, or tap one of the popular places, and the planner shows the route with every change, the walking parts, an estimated travel time and the Nol fare. It works in English, Hindi, Arabic, Urdu, Russian, German, French and Chinese, on phones and computers, with nothing to install.",
 popular="Popular trips",
 trips=["Dubai Airport (DXB Terminal 3) to Dubai Mall and Burj Khalifa","Dubai Airport (DXB Terminal 1) to Dubai Marina","Dubai Airport to JBR The Walk","Dubai Mall to Atlantis The Palm","Dubai Mall to the Gold Souk","Al Fahidi (Old Dubai) to the Museum of the Future","Dubai Marina to Mall of the Emirates and Ski Dubai","Dubai Mall to Expo City Dubai"],
 lines="Lines and stations",
 red="<b>Red Line:</b> {a} to {b}, with a branch from {c} to {d}.", branch="Branch",
 green="<b>Green Line:</b> {a} to {b}. Changes with the Red Line at Union and BurJuman.",
 tram="<b>Dubai Tram:</b> Al Sufouh to the loop at Dubai Marina and JBR. Walking links to the Metro at Dubai Marina (Sobha Realty) and Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail:</b> {a} to {b}, along the Palm Jumeirah. It is run by a private operator and is not part of the Nol system.",
 susp=" At the time of the last update the operator listed it as temporarily suspended.",
 faq="Questions",
 q=[("What are the Dubai Metro opening hours?","Usually 5:00 to midnight Monday to Thursday and Saturday, 5:00 to 1:00 on Friday night, and 8:00 to midnight on Sunday. The Tram runs about 6:00 to 1:00 (from 9:00 on Sunday). Hours change during Ramadan and on public holidays; check RTA before a late trip."),
    ("How much does the Metro cost?","Fares depend on how many zones you cross. With a Silver Nol card: AED {s0} within one zone, AED {s1} across two zones and AED {s2} for three or more. Gold Class costs AED {g0} to {g2}, a paper Red ticket AED {r0} to {r2}. The planner shows the estimate for each trip."),
    ("Can I get from the airport to the city by Metro?","Yes. Airport Terminal 1 and Terminal 3 are on the Red Line, linked to the terminals. Dubai Mall and Burj Khalifa are about 40 to 45 minutes away with no changes; Dubai Marina takes about an hour, JBR a little longer."),
    ("Is this the official RTA map?","No. This is an independent, non-commercial project and is not affiliated with RTA. Travel times are estimates based on the RTA timetable; always follow signs and announcements at the station.")],
 report="Report a problem or suggest an improvement", close="Close", langName="English"),

"hi": dict(
 file="hi.html", locale="hi_IN", dir="ltr",
 title="दुबई मेट्रो मैप और रूट प्लानर: मेट्रो, ट्राम, पाम मोनोरेल",
 desc="मुफ़्त, अनौपचारिक दुबई मेट्रो मैप और यात्रा प्लानर। एयरपोर्ट से दुबई मॉल, मरीना, JBR या अटलांटिस तक मेट्रो, ट्राम और पाम मोनोरेल से कैसे जाएँ: चरण-दर-चरण रास्ता, यात्रा का समय, Nol किराया और चलने का समय, 8 भाषाओं में।",
 ogTitle="दुबई मेट्रो मैप और रूट प्लानर",
 ogDesc="मेट्रो, ट्राम और पाम मोनोरेल: रास्ता, यात्रा का समय, Nol किराया और चलने का समय। मुफ़्त, 8 भाषाओं में।",
 h1="दुबई मेट्रो मैप और रूट प्लानर",
 intro="दुबई मेट्रो, दुबई ट्राम और पाम मोनोरेल का एक अनौपचारिक, मुफ़्त मैप। कोई जगह या स्टेशन लिखें या किसी लोकप्रिय जगह पर टैप करें, और प्लानर पूरा रास्ता दिखाएगा: हर बदलाव, पैदल चलने वाले हिस्से, अनुमानित यात्रा समय और Nol किराया। यह अंग्रेज़ी, हिंदी, अरबी, उर्दू, रूसी, जर्मन, फ़्रेंच और चीनी में, फ़ोन और कंप्यूटर दोनों पर चलता है, कुछ भी इंस्टॉल करने की ज़रूरत नहीं।",
 popular="लोकप्रिय यात्राएँ",
 trips=["दुबई एयरपोर्ट (DXB टर्मिनल 3) से दुबई मॉल और बुर्ज ख़लीफ़ा","दुबई एयरपोर्ट (DXB टर्मिनल 1) से दुबई मरीना","दुबई एयरपोर्ट से JBR The Walk","दुबई मॉल से अटलांटिस द पाम","दुबई मॉल से गोल्ड सूक","अल फ़हीदी (पुराना दुबई) से म्यूज़ियम ऑफ़ द फ़्यूचर","दुबई मरीना से मॉल ऑफ़ द एमिरेट्स और स्की दुबई","दुबई मॉल से एक्सपो सिटी दुबई"],
 lines="लाइनें और स्टेशन",
 red="<b>रेड लाइन:</b> {a} से {b} तक, और {c} से {d} तक एक शाखा।", branch="शाखा",
 green="<b>ग्रीन लाइन:</b> {a} से {b} तक। Union और BurJuman पर रेड लाइन से बदल सकते हैं।",
 tram="<b>दुबई ट्राम:</b> Al Sufouh से Dubai Marina और JBR के लूप तक। Dubai Marina (Sobha Realty) और Jumeirah Lakes Towers (DMCC) पर मेट्रो तक पैदल रास्ता।",
 mono="<b>पाम मोनोरेल:</b> {a} से {b} तक, पाम जुमेराह के साथ-साथ। इसे एक निजी कंपनी चलाती है और यह Nol सिस्टम का हिस्सा नहीं है।",
 susp=" पिछले अपडेट के समय ऑपरेटर के अनुसार सेवा अस्थायी रूप से बंद थी।",
 faq="अक्सर पूछे जाने वाले सवाल",
 q=[("दुबई मेट्रो किस समय चलती है?","आम तौर पर सोमवार से गुरुवार और शनिवार को सुबह 5:00 से आधी रात तक, शुक्रवार को सुबह 5:00 से रात 1:00 तक, और रविवार को सुबह 8:00 से आधी रात तक। ट्राम लगभग सुबह 6:00 से रात 1:00 तक चलती है (रविवार को 9:00 से)। रमज़ान और छुट्टियों में समय बदलता है; देर रात की यात्रा से पहले RTA पर देख लें।"),
    ("मेट्रो का किराया कितना है?","किराया इस पर निर्भर करता है कि आप कितने ज़ोन पार करते हैं। Silver Nol कार्ड से: एक ज़ोन में AED {s0}, दो ज़ोन में AED {s1} और तीन या अधिक ज़ोन में AED {s2}। Gold Class का किराया AED {g0} से {g2} और काग़ज़ के Red टिकट का AED {r0} से {r2} है। प्लानर हर यात्रा का अनुमानित किराया दिखाता है।"),
    ("क्या एयरपोर्ट से शहर मेट्रो से जा सकते हैं?","हाँ। Airport Terminal 1 और Terminal 3 स्टेशन रेड लाइन पर हैं और टर्मिनलों से जुड़े हैं। दुबई मॉल और बुर्ज ख़लीफ़ा बिना बदले लगभग 40 से 45 मिनट में; दुबई मरीना लगभग एक घंटे में, JBR थोड़ा ज़्यादा।"),
    ("क्या यह RTA का आधिकारिक मैप है?","नहीं। यह एक स्वतंत्र, गैर-व्यावसायिक प्रोजेक्ट है और RTA से जुड़ा नहीं है। यात्रा का समय RTA की समय-सारिणी पर आधारित अनुमान है; स्टेशन पर हमेशा संकेतों और घोषणाओं का पालन करें।")],
 report="समस्या बताएँ या सुधार सुझाएँ", close="बंद करें", langName="हिन्दी"),

"ar": dict(
 file="ar.html", locale="ar_AE", dir="rtl",
 title="خريطة مترو دبي ومخطط الرحلات: المترو والترام ومونوريل النخلة",
 desc="خريطة مجانية وغير رسمية لمترو دبي مع مخطط للرحلات. من المطار إلى دبي مول ودبي مارينا وJBR وأتلانتس بالمترو والترام ومونوريل النخلة: إرشادات خطوة بخطوة ومدة الرحلة وأسعار نول ومواعيد التشغيل، بثماني لغات.",
 ogTitle="خريطة مترو دبي ومخطط الرحلات",
 ogDesc="المترو والترام ومونوريل النخلة: الاتجاهات ومدة الرحلة وأسعار نول ومواعيد التشغيل. مجانًا وبثماني لغات.",
 h1="خريطة مترو دبي ومخطط الرحلات",
 intro="خريطة مجانية وغير رسمية لمترو دبي وترام دبي ومونوريل النخلة. اكتب مكانًا أو محطة، أو اختر أحد الأماكن الشائعة، وسيعرض المخطط المسار مع كل تبديل والأجزاء التي تُقطع سيرًا على الأقدام والمدة التقريبية للرحلة وأجرة نول. يعمل بالإنجليزية والهندية والعربية والأردية والروسية والألمانية والفرنسية والصينية، على الهاتف والكمبيوتر، دون أي تثبيت.",
 popular="رحلات شائعة",
 trips=["من مطار دبي (DXB المبنى 3) إلى دبي مول وبرج خليفة","من مطار دبي (DXB المبنى 1) إلى دبي مارينا","من مطار دبي إلى JBR The Walk","من دبي مول إلى أتلانتس النخلة","من دبي مول إلى سوق الذهب","من الفهيدي (دبي القديمة) إلى متحف المستقبل","من دبي مارينا إلى مول الإمارات وسكي دبي","من دبي مول إلى إكسبو سيتي دبي"],
 lines="الخطوط والمحطات",
 red="<b>الخط الأحمر:</b> من {a} إلى {b}، مع فرع من {c} إلى {d}.", branch="الفرع",
 green="<b>الخط الأخضر:</b> من {a} إلى {b}. التبديل إلى الخط الأحمر في محطتي Union وBurJuman.",
 tram="<b>ترام دبي:</b> من Al Sufouh إلى الحلقة عند Dubai Marina وJBR. ممرات مشاة إلى المترو عند Dubai Marina (Sobha Realty) وJumeirah Lakes Towers (DMCC).",
 mono="<b>مونوريل النخلة:</b> من {a} إلى {b} على امتداد نخلة جميرا. تديره شركة خاصة وليس جزءًا من نظام نول.",
 susp=" عند آخر تحديث، كان المشغّل يشير إلى توقف الخدمة مؤقتًا.",
 faq="أسئلة شائعة",
 q=[("ما مواعيد تشغيل مترو دبي؟","عادةً من 5:00 صباحًا حتى منتصف الليل من الاثنين إلى الخميس ويوم السبت، ومن 5:00 صباحًا حتى 1:00 بعد منتصف الليل يوم الجمعة، ومن 8:00 صباحًا حتى منتصف الليل يوم الأحد. يعمل الترام تقريبًا من 6:00 صباحًا حتى 1:00 بعد منتصف الليل (من 9:00 يوم الأحد). تتغير المواعيد في رمضان والعطلات الرسمية، لذا تحقّق من هيئة الطرق والمواصلات قبل الرحلات المتأخرة."),
    ("كم تبلغ أجرة المترو؟","تعتمد الأجرة على عدد المناطق التي تعبرها. باستخدام بطاقة نول الفضية: AED {s0} داخل منطقة واحدة، وAED {s1} عبر منطقتين، وAED {s2} لثلاث مناطق أو أكثر. تكلفة الدرجة الذهبية من AED {g0} إلى {g2}، والتذكرة الحمراء الورقية من AED {r0} إلى {r2}. يعرض المخطط الأجرة التقديرية لكل رحلة."),
    ("هل يمكن الوصول من المطار إلى المدينة بالمترو؟","نعم. محطتا Airport Terminal 1 وTerminal 3 على الخط الأحمر ومتصلتان بمباني المطار. يستغرق الوصول إلى دبي مول وبرج خليفة نحو 40 إلى 45 دقيقة دون تبديل، وإلى دبي مارينا نحو ساعة، وإلى JBR أكثر قليلًا."),
    ("هل هذه الخريطة الرسمية لهيئة الطرق والمواصلات؟","لا. هذا مشروع مستقل وغير تجاري ولا يرتبط بهيئة الطرق والمواصلات. مدة الرحلات تقديرية بناءً على جداول الهيئة، لذا اتّبع دائمًا اللافتات والإعلانات في المحطة.")],
 report="الإبلاغ عن مشكلة أو اقتراح تحسين", close="إغلاق", langName="العربية"),

"ur": dict(
 file="ur.html", locale="ur_PK", dir="rtl",
 title="دبئی میٹرو نقشہ اور روٹ پلانر: میٹرو، ٹرام، پام مونو ریل",
 desc="دبئی میٹرو کا مفت، غیر سرکاری نقشہ اور سفر پلانر۔ ایئرپورٹ سے دبئی مال، مرینا، JBR یا اٹلانٹس تک میٹرو، ٹرام اور پام مونو ریل سے کیسے جائیں: مرحلہ وار راستہ، سفر کا وقت، Nol کرایہ اور اوقاتِ کار، 8 زبانوں میں۔",
 ogTitle="دبئی میٹرو نقشہ اور روٹ پلانر",
 ogDesc="میٹرو، ٹرام اور پام مونو ریل: راستہ، سفر کا وقت، Nol کرایہ اور اوقات۔ مفت، 8 زبانوں میں۔",
 h1="دبئی میٹرو نقشہ اور روٹ پلانر",
 intro="دبئی میٹرو، دبئی ٹرام اور پام مونو ریل کا ایک غیر سرکاری، مفت نقشہ۔ کوئی جگہ یا اسٹیشن لکھیں یا کسی مقبول جگہ پر ٹیپ کریں، اور پلانر پورا راستہ دکھائے گا: ہر تبدیلی، پیدل حصے، اندازاً سفر کا وقت اور Nol کرایہ۔ یہ انگریزی، ہندی، عربی، اردو، روسی، جرمن، فرانسیسی اور چینی میں، فون اور کمپیوٹر دونوں پر چلتا ہے، کچھ انسٹال کرنے کی ضرورت نہیں۔",
 popular="مقبول سفر",
 trips=["دبئی ایئرپورٹ (DXB ٹرمینل 3) سے دبئی مال اور برج خلیفہ","دبئی ایئرپورٹ (DXB ٹرمینل 1) سے دبئی مرینا","دبئی ایئرپورٹ سے JBR The Walk","دبئی مال سے اٹلانٹس دی پام","دبئی مال سے گولڈ سوق","الفہیدی (پرانا دبئی) سے میوزیم آف دی فیوچر","دبئی مرینا سے مال آف دی ایمریٹس اور اسکی دبئی","دبئی مال سے ایکسپو سٹی دبئی"],
 lines="لائنیں اور اسٹیشن",
 red="<b>ریڈ لائن:</b> {a} سے {b} تک، اور {c} سے {d} تک ایک شاخ۔", branch="شاخ",
 green="<b>گرین لائن:</b> {a} سے {b} تک۔ Union اور BurJuman پر ریڈ لائن میں تبدیلی ہوتی ہے۔",
 tram="<b>دبئی ٹرام:</b> Al Sufouh سے Dubai Marina اور JBR کے لوپ تک۔ Dubai Marina (Sobha Realty) اور Jumeirah Lakes Towers (DMCC) پر میٹرو تک پیدل راستہ۔",
 mono="<b>پام مونو ریل:</b> {a} سے {b} تک، پام جمیرا کے ساتھ ساتھ۔ اسے ایک نجی کمپنی چلاتی ہے اور یہ Nol نظام کا حصہ نہیں۔",
 susp=" آخری اپڈیٹ کے وقت آپریٹر کے مطابق سروس عارضی طور پر معطل تھی۔",
 faq="اکثر پوچھے جانے والے سوالات",
 q=[("دبئی میٹرو کس وقت چلتی ہے؟","عام طور پر پیر سے جمعرات اور ہفتے کو صبح 5:00 سے آدھی رات تک، جمعے کو صبح 5:00 سے رات 1:00 بجے تک، اور اتوار کو صبح 8:00 سے آدھی رات تک۔ ٹرام تقریباً صبح 6:00 سے رات 1:00 بجے تک چلتی ہے (اتوار کو 9:00 سے)۔ رمضان اور تعطیلات میں اوقات بدل جاتے ہیں؛ رات دیر کے سفر سے پہلے RTA پر دیکھ لیں۔"),
    ("میٹرو کا کرایہ کتنا ہے؟","کرایہ اس پر منحصر ہے کہ آپ کتنے زون عبور کرتے ہیں۔ Silver Nol کارڈ سے: ایک زون میں AED {s0}، دو زون میں AED {s1} اور تین یا زیادہ زون میں AED {s2}۔ Gold Class کا کرایہ AED {g0} سے {g2} اور کاغذی Red ٹکٹ کا AED {r0} سے {r2} ہے۔ پلانر ہر سفر کا اندازاً کرایہ دکھاتا ہے۔"),
    ("کیا ایئرپورٹ سے شہر میٹرو سے جا سکتے ہیں؟","جی ہاں۔ Airport Terminal 1 اور Terminal 3 اسٹیشن ریڈ لائن پر ہیں اور ٹرمینلز سے جڑے ہیں۔ دبئی مال اور برج خلیفہ بغیر تبدیلی کے تقریباً 40 سے 45 منٹ میں؛ دبئی مرینا تقریباً ایک گھنٹے میں، JBR کچھ زیادہ۔"),
    ("کیا یہ RTA کا سرکاری نقشہ ہے؟","نہیں۔ یہ ایک آزاد، غیر تجارتی منصوبہ ہے اور RTA سے وابستہ نہیں۔ سفر کے اوقات RTA کے ٹائم ٹیبل پر مبنی اندازے ہیں؛ اسٹیشن پر ہمیشہ نشانات اور اعلانات پر عمل کریں۔")],
 report="مسئلہ رپورٹ کریں یا بہتری تجویز کریں", close="بند کریں", langName="اردو"),

"ru": dict(
 file="ru.html", locale="ru_RU", dir="ltr",
 title="Карта метро Дубая и планировщик маршрутов: метро, трамвай, монорельс",
 desc="Бесплатная неофициальная карта метро Дубая с построением маршрута. Как добраться из аэропорта до Dubai Mall, Марины, JBR и Atlantis на метро, трамвае и монорельсе Palm: пошаговый маршрут, время в пути, цены Nol и часы работы, на 8 языках.",
 ogTitle="Карта метро Дубая и маршруты",
 ogDesc="Метро, трамвай и монорельс Palm: как доехать, время в пути, цены Nol и часы работы. Бесплатно, на 8 языках.",
 h1="Карта метро Дубая и планировщик маршрутов",
 intro="Неофициальная бесплатная карта метро Дубая, трамвая и монорельса Palm. Введите место или станцию либо выберите популярное место, и планировщик покажет маршрут со всеми пересадками, пешими участками, примерным временем в пути и ценой по карте Nol. Сайт работает на английском, хинди, арабском, урду, русском, немецком, французском и китайском, на телефоне и компьютере, ничего устанавливать не нужно.",
 popular="Популярные маршруты",
 trips=["Из аэропорта Дубая (DXB, терминал 3) до Dubai Mall и Бурдж-Халифы","Из аэропорта Дубая (DXB, терминал 1) до Dubai Marina","Из аэропорта Дубая до JBR The Walk","От Dubai Mall до Atlantis The Palm","От Dubai Mall до Золотого рынка","От Аль-Фахиди (старый Дубай) до Музея будущего","От Dubai Marina до Mall of the Emirates и Ski Dubai","От Dubai Mall до Expo City Dubai"],
 lines="Линии и станции",
 red="<b>Красная линия:</b> от {a} до {b}, с ответвлением от {c} до {d}.", branch="Ответвление",
 green="<b>Зелёная линия:</b> от {a} до {b}. Пересадка на Красную линию на станциях Union и BurJuman.",
 tram="<b>Трамвай Дубая:</b> от Al Sufouh до кольца у Dubai Marina и JBR. Пешие переходы к метро у станций Dubai Marina (Sobha Realty) и Jumeirah Lakes Towers (DMCC).",
 mono="<b>Монорельс Palm:</b> от {a} до {b}, вдоль острова Пальма Джумейра. Им управляет частный оператор, карта Nol на нём не действует.",
 susp=" На момент последнего обновления оператор сообщал, что движение временно приостановлено.",
 faq="Частые вопросы",
 q=[("Во сколько работает метро Дубая?","Обычно с 5:00 до полуночи с понедельника по четверг и в субботу, с 5:00 до 1:00 ночи в пятницу и с 8:00 до полуночи в воскресенье. Трамвай ходит примерно с 6:00 до 1:00 (в воскресенье с 9:00). В Рамадан и праздники часы меняются; перед поздней поездкой проверьте на сайте RTA."),
    ("Сколько стоит проезд в метро?","Цена зависит от того, сколько зон вы пересекаете. По серебряной карте Nol: AED {s0} в пределах одной зоны, AED {s1} через две зоны и AED {s2} за три и больше. Gold Class стоит от AED {g0} до {g2}, бумажный Red ticket от AED {r0} до {r2}. Планировщик показывает примерную цену для каждой поездки."),
    ("Можно ли доехать из аэропорта в город на метро?","Да. Станции Airport Terminal 1 и Terminal 3 находятся на Красной линии и соединены с терминалами. До Dubai Mall и Бурдж-Халифы около 40–45 минут без пересадок, до Dubai Marina около часа, до JBR немного дольше."),
    ("Это официальная карта RTA?","Нет. Это независимый некоммерческий проект, не связанный с RTA. Время в пути рассчитано по расписанию RTA и является оценкой; на станции всегда ориентируйтесь на указатели и объявления.")],
 report="Сообщить об ошибке или предложить улучшение", close="Закрыть", langName="Русский"),

"de": dict(
 file="de.html", locale="de_DE", dir="ltr",
 title="Dubai Metro Karte &amp; Routenplaner: Metro, Tram, Palm Monorail",
 desc="Kostenlose, inoffizielle Karte der Dubai Metro mit Routenplaner. Vom Flughafen zur Dubai Mall, zur Marina, nach JBR oder zum Atlantis mit Metro, Tram und Palm Monorail: Wegbeschreibung Schritt für Schritt, Fahrzeiten, Nol-Preise und Betriebszeiten, in 8 Sprachen.",
 ogTitle="Dubai Metro Karte &amp; Routenplaner",
 ogDesc="Metro, Tram und Palm Monorail: Wegbeschreibung, Fahrzeiten, Nol-Preise und Betriebszeiten. Kostenlos, in 8 Sprachen.",
 h1="Dubai Metro Karte und Routenplaner",
 intro="Eine inoffizielle, kostenlose Karte der Dubai Metro, der Dubai Tram und der Palm Monorail. Geben Sie einen Ort oder eine Station ein oder tippen Sie auf ein beliebtes Ziel: Der Planer zeigt die Route mit allen Umstiegen, den Fußwegen, einer geschätzten Fahrzeit und dem Nol-Preis. Er funktioniert auf Englisch, Hindi, Arabisch, Urdu, Russisch, Deutsch, Französisch und Chinesisch, auf Handy und Computer, ohne Installation.",
 popular="Beliebte Strecken",
 trips=["Flughafen Dubai (DXB Terminal 3) zur Dubai Mall und zum Burj Khalifa","Flughafen Dubai (DXB Terminal 1) zur Dubai Marina","Flughafen Dubai nach JBR The Walk","Dubai Mall zum Atlantis The Palm","Dubai Mall zum Gold Souk","Al Fahidi (Altstadt) zum Museum of the Future","Dubai Marina zur Mall of the Emirates und zu Ski Dubai","Dubai Mall zur Expo City Dubai"],
 lines="Linien und Stationen",
 red="<b>Rote Linie:</b> {a} bis {b}, mit einem Abzweig von {c} nach {d}.", branch="Abzweig",
 green="<b>Grüne Linie:</b> {a} bis {b}. Umstieg zur Roten Linie in Union und BurJuman.",
 tram="<b>Dubai Tram:</b> Al Sufouh bis zur Schleife an Dubai Marina und JBR. Fußwege zur Metro an Dubai Marina (Sobha Realty) und Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail:</b> {a} bis {b}, entlang der Palm Jumeirah. Sie wird von einem privaten Betreiber betrieben und gehört nicht zum Nol-System.",
 susp=" Zum Zeitpunkt der letzten Aktualisierung meldete der Betreiber, dass der Betrieb vorübergehend eingestellt ist.",
 faq="Häufige Fragen",
 q=[("Wann fährt die Dubai Metro?","In der Regel Montag bis Donnerstag und Samstag von 5:00 bis Mitternacht, freitags von 5:00 bis 1:00 Uhr nachts und sonntags von 8:00 bis Mitternacht. Die Tram fährt etwa von 6:00 bis 1:00 Uhr (sonntags ab 9:00). Im Ramadan und an Feiertagen gelten andere Zeiten; prüfen Sie vor einer späten Fahrt die Angaben der RTA."),
    ("Was kostet die Metro?","Der Preis hängt davon ab, wie viele Zonen Sie durchfahren. Mit der Silver-Nol-Karte: AED {s0} innerhalb einer Zone, AED {s1} über zwei Zonen und AED {s2} ab drei Zonen. Gold Class kostet AED {g0} bis {g2}, ein Red Ticket aus Papier AED {r0} bis {r2}. Der Planer zeigt für jede Fahrt den geschätzten Preis."),
    ("Kommt man mit der Metro vom Flughafen in die Stadt?","Ja. Airport Terminal 1 und Terminal 3 liegen an der Roten Linie und sind mit den Terminals verbunden. Bis zur Dubai Mall und zum Burj Khalifa sind es etwa 40 bis 45 Minuten ohne Umstieg, bis zur Dubai Marina etwa eine Stunde, bis JBR etwas länger."),
    ("Ist das die offizielle Karte der RTA?","Nein. Dies ist ein unabhängiges, nicht kommerzielles Projekt ohne Verbindung zur RTA. Die Fahrzeiten sind Schätzungen auf Grundlage des RTA-Fahrplans; achten Sie an der Station immer auf Schilder und Durchsagen.")],
 report="Fehler melden oder Verbesserung vorschlagen", close="Schließen", langName="Deutsch"),

"zh": dict(
 file="zh.html", locale="zh_CN", dir="ltr",
 title="迪拜地铁线路图与路线规划：地铁、有轨电车、棕榈岛单轨",
 desc="免费的非官方迪拜地铁线路图和路线规划工具。从机场前往迪拜购物中心、迪拜码头、JBR 或亚特兰蒂斯，乘坐地铁、有轨电车和棕榈岛单轨：分步路线、行程时间、Nol 票价和运营时间，支持 8 种语言。",
 ogTitle="迪拜地铁线路图与路线规划",
 ogDesc="地铁、有轨电车和棕榈岛单轨：路线指引、行程时间、Nol 票价和运营时间。免费，支持 8 种语言。",
 h1="迪拜地铁线路图与路线规划",
 intro="这是一份免费的非官方迪拜地铁、迪拜有轨电车和棕榈岛单轨线路图。输入地点或车站，或点选热门地点，规划工具就会显示完整路线，包括每次换乘、步行路段、预计行程时间和 Nol 票价。支持英语、印地语、阿拉伯语、乌尔都语、俄语、德语、法语和中文，手机和电脑均可使用，无需安装。",
 popular="热门路线",
 trips=["迪拜机场（DXB 3 号航站楼）到迪拜购物中心和哈利法塔","迪拜机场（DXB 1 号航站楼）到迪拜码头","迪拜机场到 JBR The Walk","迪拜购物中心到亚特兰蒂斯酒店","迪拜购物中心到黄金市场","Al Fahidi 历史街区（老城）到未来博物馆","迪拜码头到阿联酋购物中心和迪拜滑雪场","迪拜购物中心到迪拜世博城"],
 lines="线路与车站",
 red="<b>红线：</b>{a} 至 {b}，另有一条支线从 {c} 至 {d}。", branch="支线",
 green="<b>绿线：</b>{a} 至 {b}。可在 Union 和 BurJuman 站换乘红线。",
 tram="<b>迪拜有轨电车：</b>从 Al Sufouh 至 Dubai Marina 和 JBR 的环线。在 Dubai Marina（Sobha Realty）和 Jumeirah Lakes Towers（DMCC）可步行换乘地铁。",
 mono="<b>棕榈岛单轨：</b>{a} 至 {b}，沿朱美拉棕榈岛运行。由私营公司运营，不属于 Nol 系统。",
 susp="截至最近一次更新，运营方显示该线路暂停运营。",
 faq="常见问题",
 q=[("迪拜地铁的运营时间是几点？","通常周一至周四及周六为 5:00 至午夜，周五为 5:00 至次日 1:00，周日为 8:00 至午夜。有轨电车约 6:00 至次日 1:00 运营（周日 9:00 起）。斋月和节假日时间会调整，深夜出行前请查看 RTA 信息。"),
    ("乘坐地铁要多少钱？","票价取决于跨越的区数。使用 Silver Nol 卡：同一区内 AED {s0}，跨两个区 AED {s1}，三个区及以上 AED {s2}。Gold Class 为 AED {g0} 至 {g2}，纸质 Red 票为 AED {r0} 至 {r2}。规划工具会为每次行程显示估算票价。"),
    ("可以从机场乘地铁进城吗？","可以。Airport Terminal 1 和 Terminal 3 站位于红线上，与航站楼相连。到迪拜购物中心和哈利法塔约 40 至 45 分钟，无需换乘；到迪拜码头约一小时，到 JBR 稍长一些。"),
    ("这是 RTA 的官方地图吗？","不是。这是一个独立的非商业项目，与 RTA 无关。行程时间根据 RTA 时刻表估算，请始终以车站的指示牌和广播为准。")],
 report="报告问题或提出改进建议", close="关闭", langName="中文"),

"fr": dict(
 file="fr.html", locale="fr_FR", dir="ltr",
 title="Plan du métro de Dubaï et calcul d'itinéraire : métro, tram, monorail",
 desc="Plan gratuit et non officiel du métro de Dubaï avec calcul d'itinéraire. De l'aéroport à Dubai Mall, la Marina, JBR ou l'Atlantis en métro, tramway et Palm Monorail : itinéraire pas à pas, temps de trajet, tarifs Nol et horaires, en 8 langues.",
 ogTitle="Plan du métro de Dubaï et itinéraires",
 ogDesc="Métro, tramway et Palm Monorail : itinéraires, temps de trajet, tarifs Nol et horaires. Gratuit, en 8 langues.",
 h1="Plan du métro de Dubaï et calcul d'itinéraire",
 intro="Un plan gratuit et non officiel du métro de Dubaï, du tramway et du Palm Monorail. Saisissez un lieu ou une station, ou touchez un lieu populaire : l'outil affiche l'itinéraire avec chaque correspondance, les trajets à pied, une estimation du temps de trajet et le tarif Nol. Il fonctionne en anglais, hindi, arabe, ourdou, russe, allemand, français et chinois, sur téléphone et ordinateur, sans rien installer.",
 popular="Trajets populaires",
 trips=["Aéroport de Dubaï (DXB, terminal 3) vers Dubai Mall et Burj Khalifa","Aéroport de Dubaï (DXB, terminal 1) vers Dubai Marina","Aéroport de Dubaï vers JBR The Walk","Dubai Mall vers Atlantis The Palm","Dubai Mall vers le souk de l'or","Al Fahidi (vieux Dubaï) vers le Musée du Futur","Dubai Marina vers Mall of the Emirates et Ski Dubai","Dubai Mall vers Expo City Dubai"],
 lines="Lignes et stations",
 red="<b>Ligne rouge :</b> de {a} à {b}, avec un embranchement de {c} à {d}.", branch="Embranchement",
 green="<b>Ligne verte :</b> de {a} à {b}. Correspondance avec la ligne rouge à Union et BurJuman.",
 tram="<b>Tramway de Dubaï :</b> d'Al Sufouh jusqu'à la boucle de Dubai Marina et JBR. Liaisons à pied avec le métro à Dubai Marina (Sobha Realty) et Jumeirah Lakes Towers (DMCC).",
 mono="<b>Palm Monorail :</b> de {a} à {b}, le long de Palm Jumeirah. Il est exploité par un opérateur privé et ne fait pas partie du système Nol.",
 susp=" Lors de la dernière mise à jour, l'opérateur indiquait que le service était temporairement suspendu.",
 faq="Questions fréquentes",
 q=[("Quels sont les horaires du métro de Dubaï ?","En général de 5 h à minuit du lundi au jeudi et le samedi, de 5 h à 1 h dans la nuit du vendredi, et de 8 h à minuit le dimanche. Le tramway circule environ de 6 h à 1 h (à partir de 9 h le dimanche). Les horaires changent pendant le ramadan et les jours fériés ; vérifiez auprès de la RTA avant un trajet tardif."),
    ("Combien coûte le métro ?","Le prix dépend du nombre de zones traversées. Avec une carte Nol Silver : AED {s0} dans une zone, AED {s1} sur deux zones et AED {s2} pour trois zones ou plus. La Gold Class coûte de AED {g0} à {g2}, le ticket papier Red de AED {r0} à {r2}. L'outil indique une estimation pour chaque trajet."),
    ("Peut-on aller de l'aéroport au centre en métro ?","Oui. Les stations Airport Terminal 1 et Terminal 3 sont sur la ligne rouge et reliées aux terminaux. Dubai Mall et Burj Khalifa sont à environ 40 à 45 minutes sans correspondance ; Dubai Marina à environ une heure, JBR un peu plus."),
    ("Est-ce le plan officiel de la RTA ?","Non. C'est un projet indépendant et non commercial, sans lien avec la RTA. Les temps de trajet sont des estimations basées sur les horaires de la RTA ; suivez toujours la signalétique et les annonces en station.")],
 report="Signaler un problème ou proposer une amélioration", close="Fermer", langName="Français"),
}
ORDER=["en","hi","ar","ur","ru","de","zh","fr"]
